### ISSUE TITLE
能否给出锕系元素U和Pu的轨道赝势

### ISSUE THREAD

**Issue by songruipku** [abacusmodeling/abacus-develop#330]
### Background

目前研究广泛，需求迫切的两种锕系元素U和Pu的轨道赝势仍然缺乏，希望能用ABACUS做相关研究。

### Describe the solution you'd like

在可供下载的轨道赝势库中增加U和Pu的赝势。

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment]
we indeed have pseudopotential for Actinides, but orbitals are somewhat hard to generate presently. 
Additionally, it is strongly recommended transfer to this repo:
https://github.com/deepmodeling/abacus-develop/issues

**Comment by songruipku** [comment]
好的，感谢！
请问现在是已经有摸守恒赝势，但是轨道还很难生成吗？
能否分享一下相关的模守恒赝势呢？我可以做些测试。




濠上
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "abacusmodeling/abacus-develop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月26日(星期四) 下午5:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [abacusmodeling/abacus-develop] 能否给出锕系元素U和Pu的轨道赝势 (Issue #330)





 
we indeed have pseudopotential for Actinides, but orbitals are somewhat hard to generate presently.
 Additionally, it is strongly recommended transfer to this repo:
 https://github.com/deepmodeling/abacus-develop/issues

**Comment by kirk0830** [comment]
@songruipku You can find those norm-conserving pseudopotential file in the first link I posted in my previous comment. As for orbital, yes, because presently ABACUS numerical atomic orbital generation still relies on PW scf calculation, which means, many more basis function than other, plus the stiffness of those pseudopotentials, the generation of orbitals is extremely hard. 
I guess it will be easier after our 3.0 version orbital, but now it is still a work in progress.

As for test, please directly refer to the test result posted on ABACUS Pseudopotential Nao Square, here I post the link of element Ac:
https://[kirk0830.github.io/ABACUS-Pseudopot-Nao-Square/pseudopotential/results/2024-04-30/Ac.html](https://kirk0830.github.io/ABACUS-Pseudopot-Nao-Square/pseudopotential/results/2024-04-30/Ac.html)
:)
